//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPENSACION
    {
        public decimal id { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string nombreEmpresa { get; set; }
        public string pais { get; set; }
        public string mail { get; set; }
        public string toneladas { get; set; }
        public string compensacion1 { get; set; }
    }
}
